###
POST http://localhost:3333/sensor 
Content-Type: application/json

{
  "temperature": 24.5,
  "humidity": 55.0,
  "co2Level": 400.0,
  "coLevel": 0.5,
  "ch4Level": 1.8,
  "pm25": 12.0,
  "pm10": 20.0,
  "nh3Level": 0.03,
  "no2Level": 0.02,
  "ozoneLevel": 0.04,
  "enterpriseId": 1
}

### 
GET http://localhost:3333/sensor/1


###
GET http://localhost:3333/enterprises

###
POST http://localhost:3333/enterprises 
Content-Type: application/json

{
  "name": "N'Gola",
  "email": "ngola@gmail.com",
  "phoneNumber": "+244 945 994 478",
  "address": "Angola, Huíla - Lubango, Bairro Mapunda",
  "industryType": "Secundário de Produção de Alimentos e Bebidas"
}
